name: my_first_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase / GA4
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0

  # REST API
  http: ^1.6.0

  # WebView
  webview_flutter: ^4.7.0

  # Image cache
  cached_network_image: ^3.3.1

  # Shared prefs
  shared_preferences: ^2.2.2

  # YouTube
  youtube_player_flutter: ^9.0.0

  # HTML
  flutter_html: ^3.0.0
  flutter_html_table: ^3.0.0

  # Visibility
  visibility_detector: ^0.4.0

  # HTML parser
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
